# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-18 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20200118_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_day',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
