# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20200119_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_1_votes',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_votes',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
