# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20200119_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userright',
            name='match_voted',
            field=models.CharField(blank=True, default=None, max_length=15000, null=True),
        ),
    ]
