# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_userright_match_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_1_votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
